import { 
  User, 
  Activity, 
  MessageSquare, 
  History, 
  Search, 
  Stethoscope, 
  FileText, 
  Pill, 
  Lightbulb, 
  ShieldAlert,
  Save,
  Printer,
  Share2,
  FileJson,
  Menu,
  X,
  Plus,
  ChevronDown,
  Clock,
  Info,
  Trash2
} from "lucide-react";

export const ICONS = {
  Patient: User,
  Vitals: Activity,
  Complaints: MessageSquare,
  History: History,
  Examination: Search,
  Diagnosis: Stethoscope,
  Investigations: FileText,
  Medicines: Pill,
  Advice: Lightbulb,
  Interactions: ShieldAlert,
  Search: Search,
  Pill: Pill,
  ShieldAlert: ShieldAlert,
  Save: Save,
  Print: Printer,
  Share: Share2,
  Template: FileJson,
  Menu: Menu,
  Close: X,
  Plus: Plus,
  ChevronDown: ChevronDown,
  Clock: Clock,
  Info: Info,
  Delete: Trash2
};